### ISSUE TITLE
Search for friends

### ISSUE THREAD

**Issue by MAGistR-bit** [liawdrti/liawdrti#1]
Hello, @liawdrti!
You have a great portfolio. Are you looking for friends, aren't you?
@liawdrti, can we work together? I am a beginner, so any experience will be useful for me.
I am learning Java. 
Have a nice day!

**Comment by liawdrti** [comment]
Hello, @MAGistR-bit 
Im sorry for replying u late. I just see ur message. 
By the way, thank you so much! 
Sure, we can be friends and we can work together 😊 Have a nice day too!

**Comment by MAGistR-bit** [comment]
@liawdrti, do you have a project that you can work on together?
I'm learning Java.
